### PR TITLE
chore(*): cherrypick from master to release-1.2

### PR DESCRIPTION
**Pull request by lichuan0620**
**What this PR does / why we need it**:

Handpick #56 and #57 to release-1.2

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @supereagle @jianglinjian 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
#56 is only for CPS v2.10, why need to cherry pick it into the old branch?

**Comment by lichuan0620** [comment]
@supereagle the plan is to continue using release-1.2 for 2.10. No code was changed and there were no incompatible changes, so we shouldn't need a new release.

**Pull request merged**
