### PR TITLE
fix(logstash): add logstash config

### PR DESCRIPTION
**Pull request by moshuipan**
**What this PR does / why we need it**:

- add logstash config
- add custom fields
- add multiline pattern config
**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #https://github.com/caicloud/prod-issue/issues/666#issuecomment-500391163 , https://github.com/caicloud/prod-issue/issues/671

**Special notes for your reviewer**:

/cc @lichuan0620 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lichuan0620** [comment]
有测过么？在哪个环境测的？

**Comment by moshuipan** [comment]
> 有测过么？在哪个环境测的？

发给星巴克那边，在他们的测试环境里测了

**Pull request merged**
